/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.WorkExperience;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JPanel;

/**
 *
 * @author Giridhar
 */
public class WorkExperienceJPanel extends javax.swing.JPanel {

    /**
     * Creates new form WorkExperienceJPanel
     */
    private JPanel userProcessContainer;
    private String x;
    public WorkExperienceJPanel(JPanel usp, String sid) {
        initComponents();
        this.x = sid;
        this.userProcessContainer = usp;
        lblStudID.setText(x);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        txtEndDate = new javax.swing.JTextField();
        txtWorkID = new javax.swing.JTextField();
        txtCompany = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        txtSkill = new javax.swing.JTextField();
        txtStartDate = new javax.swing.JTextField();
        lblCompany = new javax.swing.JLabel();
        lblWorkId1 = new javax.swing.JLabel();
        lblTitle1 = new javax.swing.JLabel();
        lblStartDate1 = new javax.swing.JLabel();
        lblEndDate1 = new javax.swing.JLabel();
        lblPlaceOfWork1 = new javax.swing.JLabel();
        lblSkill = new javax.swing.JLabel();
        txtPlaceOfWork = new javax.swing.JTextField();
        title = new javax.swing.JLabel();
        title1 = new javax.swing.JLabel();
        lblStudID = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        progressBar = new javax.swing.JProgressBar();

        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtEndDate.setText("MM-DD-YYYY");
        txtEndDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtEndDateMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtEndDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 160, -1));
        jInternalFrame1.getContentPane().add(txtWorkID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 160, -1));

        txtCompany.setText("Enter Company Name");
        txtCompany.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtCompanyMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 160, -1));

        txtTitle.setText("Enter Your Role");
        txtTitle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtTitleMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 160, -1));

        txtSkill.setText("Enter 1 proficient skill");
        txtSkill.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtSkillMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtSkill, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 160, -1));

        txtStartDate.setText("MM-DD-YYYY");
        txtStartDate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtStartDateMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 160, -1));

        lblCompany.setText("Company :");
        jInternalFrame1.getContentPane().add(lblCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lblWorkId1.setText("Work ID :");
        jInternalFrame1.getContentPane().add(lblWorkId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        lblTitle1.setText("Title");
        jInternalFrame1.getContentPane().add(lblTitle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        lblStartDate1.setText("Start Date :");
        jInternalFrame1.getContentPane().add(lblStartDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblEndDate1.setText("End Date :");
        jInternalFrame1.getContentPane().add(lblEndDate1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        lblPlaceOfWork1.setText("Place of Work :");
        jInternalFrame1.getContentPane().add(lblPlaceOfWork1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        lblSkill.setText("Skill :");
        jInternalFrame1.getContentPane().add(lblSkill, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        txtPlaceOfWork.setText("Location of the company");
        txtPlaceOfWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPlaceOfWorkMouseClicked(evt);
            }
        });
        jInternalFrame1.getContentPane().add(txtPlaceOfWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 160, -1));

        title.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        title.setText("Work Experience");
        jInternalFrame1.getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        title1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        title1.setText("Student:");
        jInternalFrame1.getContentPane().add(title1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 70, -1));

        lblStudID.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        jInternalFrame1.getContentPane().add(lblStudID, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 90, 10));

        jScrollPane1.setViewportView(jInternalFrame1);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel10.setText("Application Progress Bar");

        progressBar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        progressBar.setBorderPainted(false);
        progressBar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addComponent(btnSave)))
                .addContainerGap(237, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(84, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String cname= txtCompany.getText();
        String wid= txtWorkID.getText();
        String title = txtTitle.getText();
        String strt_date = txtStartDate.getText();
        String end_date = txtEndDate.getText();
        String work_place = txtPlaceOfWork.getText();
        String skill = txtSkill.getText();
        
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/Admin_Database?zeroDateTimeBehavior=CONVERT_TO_NULL","root","password");
        
            
            
            String sql = "INSERT INTO WorkExperience(StudentID,company,title,StartDate,EndDate,PlaceOfWork)" +
                     "VALUES (?,?, ?, ?, ?, ?)";
            String sql2 = "INSERT INTO skill(StudentID,SkillName) " + 
                    "VALUES (?,?)";
        PreparedStatement pstmt = conn.prepareStatement(sql);
        PreparedStatement pstmt2 = conn.prepareStatement(sql2);
        
        pstmt.setString(1, x);        
        pstmt.setString(2, cname);
        pstmt.setString(3, title);
        pstmt.setString(4, strt_date);
        pstmt.setString(5, end_date);
        pstmt.setString(6, work_place);   
        
        pstmt2.setString(1, x);
        pstmt2.setString(2, skill);
        
        int rowsInserted = pstmt.executeUpdate();
        int rowsInserted2 = pstmt2.executeUpdate();
        if (rowsInserted > 0) {
            System.out.println("Work Profile is inserted successfully for the student");
            }
        if (rowsInserted > 0) {
            System.out.println("Skill is inserted successfully for the student");
            }
        }
        catch(Exception e){
        System.out.println(e.getMessage());            
        }
        progressBar.setValue(75);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtSkillMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtSkillMouseClicked
        // TODO add your handling code here:
        txtSkill.setText("");
    }//GEN-LAST:event_txtSkillMouseClicked

    private void txtCompanyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtCompanyMouseClicked
        // TODO add your handling code here:
        txtCompany.setText("");
    }//GEN-LAST:event_txtCompanyMouseClicked

    private void txtTitleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtTitleMouseClicked
        // TODO add your handling code here:
        txtTitle.setText("");
    }//GEN-LAST:event_txtTitleMouseClicked

    private void txtStartDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtStartDateMouseClicked
        // TODO add your handling code here:
        txtStartDate.setText("");
    }//GEN-LAST:event_txtStartDateMouseClicked

    private void txtEndDateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtEndDateMouseClicked
        // TODO add your handling code here:
        txtEndDate.setText("");
    }//GEN-LAST:event_txtEndDateMouseClicked

    private void txtPlaceOfWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPlaceOfWorkMouseClicked
        // TODO add your handling code here:
        txtPlaceOfWork.setText("");
    }//GEN-LAST:event_txtPlaceOfWorkMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblEndDate1;
    private javax.swing.JLabel lblPlaceOfWork1;
    private javax.swing.JLabel lblSkill;
    private javax.swing.JLabel lblStartDate1;
    private javax.swing.JLabel lblStudID;
    private javax.swing.JLabel lblTitle1;
    private javax.swing.JLabel lblWorkId1;
    private javax.swing.JProgressBar progressBar;
    private javax.swing.JLabel title;
    private javax.swing.JLabel title1;
    private javax.swing.JTextField txtCompany;
    private javax.swing.JTextField txtEndDate;
    private javax.swing.JTextField txtPlaceOfWork;
    private javax.swing.JTextField txtSkill;
    private javax.swing.JTextField txtStartDate;
    private javax.swing.JTextField txtTitle;
    private javax.swing.JTextField txtWorkID;
    // End of variables declaration//GEN-END:variables
}
